# To build and deploy to Cloud Run, run from this directory:
# $ gcloud builds submit app --config=cloudbuild.yaml 
steps:
  # Build app
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '.', '-t', 'us-central1-docker.pkg.dev/strategic-ivy-347916/fancy-store-python/fancy-store-python:${COMMIT_SHA}', '-t', 'us-central1-docker.pkg.dev/strategic-ivy-347916/fancy-store-python/fancy-store-python','-f', 'Dockerfile']
    dir: 'app'  
    id: build
  # Run unit tests
  - name: us-central1-docker.pkg.dev/strategic-ivy-347916/fancy-store-python/fancy-store-python
    entrypoint: python
    args: ["-m","pytest","unit_tests.py"]
    dir: 'app'
    id: test
  # Push docker image and save image digest for kritis check
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/strategic-ivy-347916/fancy-store-python/fancy-store-python']
    id: push
  # Create release in Google Cloud Deploy
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args: 
      [
        "beta", "deploy", "releases", "create", "rel-${SHORT_SHA}",
        "--delivery-pipeline", "fancy-store-python-pipeline",
        "--region", "us-central1",
        "--annotations", "commitId=${REVISION_ID}",
        "--images", "fancy-store-python=us-central1-docker.pkg.dev/strategic-ivy-347916/fancy-store-python/fancy-store-python:${COMMIT_SHA}"
      ]
