# To build and deploy to Cloud Run, run from this directory:
# $ gcloud builds submit app --config=cloudbuild.yaml 
steps:
  # Build app
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '.', '-t', 'us-central1-docker.pkg.dev/strategic-ivy-347916/fancy-store-python/fancy-store-python:${COMMIT_SHA}', '-t', 'us-central1-docker.pkg.dev/strategic-ivy-347916/fancy-store-python/fancy-store-python','-f', 'Dockerfile']
    dir: 'app'  
    id: build
  # Run unit tests
  - name: us-central1-docker.pkg.dev/strategic-ivy-347916/fancy-store-python/fancy-store-python
    entrypoint: python
    args: ["-m","pytest","unit_tests.py"]
    dir: 'app'
    id: test
  # Verify code with sonarqube - Quality gate
  - name: 'gcr.io/strategic-ivy-347916/sonar-scanner:latest'
    entrypoint: 'bash'
    args:
    - -c
    - /launch.sh -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$$SONAR_TOKEN -Dsonar.projectKey=$$SONAR_PROJECT_KEY -Dsonar.organization=$$SONAR_ORG -Dsonar.sources=./app -Dsonar.qualitygate.wait=false
    secretEnv: ['SONAR_TOKEN','SONAR_ORG','SONAR_PROJECT_KEY']
  # Push docker image and save image digest for kritis check
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/strategic-ivy-347916/fancy-store-python/fancy-store-python']
    id: push
  # Create release in Google Cloud Deploy
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args: 
      [
        "beta", "deploy", "releases", "create", "rel-${SHORT_SHA}",
        "--delivery-pipeline", "fancy-store-python-pipeline",
        "--region", "us-central1",
        "--annotations", "commitId=${REVISION_ID}",
        "--images", "fancy-store-python=us-central1-docker.pkg.dev/strategic-ivy-347916/fancy-store-python/fancy-store-python:${COMMIT_SHA}"
      ]
availableSecrets:
  secretManager:
  - versionName: projects/strategic-ivy-347916/secrets/sonar_token/versions/1
    env: 'SONAR_TOKEN'
  - versionName: projects/strategic-ivy-347916/secrets/sonar_org/versions/1
    env: 'SONAR_ORG'
  - versionName: projects/strategic-ivy-347916/secrets/sonar_project_key/versions/1
    env: 'SONAR_PROJECT_KEY'
